# Generated by Django 3.1.2 on 2020-11-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Fotovoltic', 'Fotovoltic'), ('Design', 'Design')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('appt_date', models.DateTimeField(verbose_name='appointment date')),
            ],
        ),
    ]
