# Generated by Django 3.1.2 on 2020-11-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20201101_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='billing',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='project',
            name='place',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Comertial', 'Comertial'), ('Industrial', 'Industrial'), ('Medium Voltage Industrial', 'Medium Voltage Industrial'), ('Large Scale', 'Large Scale')], max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
